// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: 'Popular Tools',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'pencil-ruler',
        subtitle: 'Merge, Split, Organize, Delete, Rotate, Add Blank Pages, Extract and Duplicate in an unified interface.',
      },
      {
        href: import.meta.env.BASE_URL + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'combine',
        subtitle: 'Combine multiple PDFs into one file. Preserves Bookmarks.',
      },
      {
        href: import.meta.env.BASE_URL + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'zap',
        subtitle: 'Reduce the file size of your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'pocket-knife',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs',
      },
      {
        href: import.meta.env.BASE_URL + 'jpg-to-pdf.html',
        name: 'JPG to PDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more JPG images.',
      },
      {
        href: import.meta.env.BASE_URL + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'pen-tool',
        subtitle: 'Draw, type, or upload your signature.',
      },
      {
        href: import.meta.env.BASE_URL + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'crop',
        subtitle: 'Trim the margins of every page in your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ungroup',
        subtitle: 'Save a selection of pages as new files.',
      },
      {
        href: import.meta.env.BASE_URL + 'organize-pdf.html',
        name: 'Duplicate & Organize',
        icon: 'files',
        subtitle: 'Duplicate, reorder, and delete pages.',
      },
      {
        href: import.meta.env.BASE_URL + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'trash-2',
        subtitle: 'Remove specific pages from your document.',
      },
    ],
  },
  {
    name: 'Edit & Annotate',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'edit-pdf.html',
        name: 'PDF Editor',
        icon: 'pocket-knife',
        subtitle:
          'Annotate, highlight, redact, comment, add shapes/images, search, and view PDFs.',
      },
      {
        href: import.meta.env.BASE_URL + 'bookmark.html',
        name: 'Edit Bookmarks',
        icon: 'bookmark',
        subtitle: 'Add, edit, import, delete and extract PDF bookmarks.',
      },
      {
        href: import.meta.env.BASE_URL + 'table-of-contents.html',
        name: 'Table of Contents',
        icon: 'list',
        subtitle: 'Generate a table of contents page from PDF bookmarks.',
      },
      {
        href: import.meta.env.BASE_URL + 'page-numbers.html',
        name: 'Page Numbers',
        icon: 'list-ordered',
        subtitle: 'Insert page numbers into your document.',
      },
      {
        href: import.meta.env.BASE_URL + 'add-watermark.html',
        name: 'Add Watermark',
        icon: 'droplets',
        subtitle: 'Stamp text or an image over your PDF pages.',
      },
      {
        href: import.meta.env.BASE_URL + 'header-footer.html',
        name: 'Header & Footer',
        icon: 'pilcrow',
        subtitle: 'Add text to the top and bottom of pages.',
      },
      {
        href: import.meta.env.BASE_URL + 'invert-colors.html',
        name: 'Invert Colors',
        icon: 'contrast',
        subtitle: 'Create a "dark mode" version of your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'background-color.html',
        name: 'Background Color',
        icon: 'palette',
        subtitle: 'Change the background color of your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'text-color.html',
        name: 'Change Text Color',
        icon: 'type',
        subtitle: 'Change the color of text in your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'sign-pdf.html',
        name: 'Sign PDF',
        icon: 'pen-tool',
        subtitle: 'Draw, type, or upload your signature.',
      },
      {
        href: import.meta.env.BASE_URL + 'add-stamps.html',
        name: 'Add Stamps',
        icon: 'stamp',
        subtitle: 'Add image stamps to your PDF using the annotation toolbar.',
      },
      {
        href: import.meta.env.BASE_URL + 'remove-annotations.html',
        name: 'Remove Annotations',
        icon: 'eraser',
        subtitle: 'Strip comments, highlights, and links.',
      },
      {
        href: import.meta.env.BASE_URL + 'crop-pdf.html',
        name: 'Crop PDF',
        icon: 'crop',
        subtitle: 'Trim the margins of every page in your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'form-filler.html',
        name: 'PDF Form Filler',
        icon: 'square-pen',
        subtitle: 'Fill in forms directly in the browser. Also supports XFA forms.',
      },
      {
        href: import.meta.env.BASE_URL + 'form-creator.html',
        name: 'Create PDF Form',
        icon: 'file-input',
        subtitle: 'Create fillable PDF forms with drag-and-drop text fields.',
      },
      {
        href: import.meta.env.BASE_URL + 'remove-blank-pages.html',
        name: 'Remove Blank Pages',
        icon: 'file-minus-2',
        subtitle: 'Automatically detect and delete blank pages.',
      },
    ],
  },
  {
    name: 'Convert to PDF',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'image-to-pdf.html',
        name: 'Image to PDF',
        icon: 'images',
        subtitle: 'Convert JPG, PNG, WebP, BMP, TIFF, SVG, HEIC to PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'jpg-to-pdf.html',
        name: 'JPG to PDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more JPG images.',
      },
      {
        href: import.meta.env.BASE_URL + 'png-to-pdf.html',
        name: 'PNG to PDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more PNG images.',
      },
      {
        href: import.meta.env.BASE_URL + 'webp-to-pdf.html',
        name: 'WebP to PDF',
        icon: 'image-up',
        subtitle: 'Create a PDF from one or more WebP images.',
      },
      {
        href: import.meta.env.BASE_URL + 'svg-to-pdf.html',
        name: 'SVG to PDF',
        icon: 'pen-tool',
        subtitle: 'Create a PDF from one or more SVG images.',
      },
      {
        href: import.meta.env.BASE_URL + 'bmp-to-pdf.html',
        name: 'BMP to PDF',
        icon: 'image',
        subtitle: 'Create a PDF from one or more BMP images.',
      },
      {
        href: import.meta.env.BASE_URL + 'heic-to-pdf.html',
        name: 'HEIC to PDF',
        icon: 'smartphone',
        subtitle: 'Create a PDF from one or more HEIC images.',
      },
      {
        href: import.meta.env.BASE_URL + 'tiff-to-pdf.html',
        name: 'TIFF to PDF',
        icon: 'layers',
        subtitle: 'Create a PDF from one or more TIFF images.',
      },
      {
        href: import.meta.env.BASE_URL + 'txt-to-pdf.html',
        name: 'Text to PDF',
        icon: 'file-pen',
        subtitle: 'Convert a plain text file into a PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'json-to-pdf.html',
        name: 'JSON to PDF',
        icon: 'file-code',
        subtitle: 'Convert JSON files to PDF format.',
      },
    ],
  },
  {
    name: 'Convert from PDF',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'pdf-to-jpg.html',
        name: 'PDF to JPG',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a JPG image.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-png.html',
        name: 'PDF to PNG',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a PNG image.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-webp.html',
        name: 'PDF to WebP',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a WebP image.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-bmp.html',
        name: 'PDF to BMP',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a BMP image.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-tiff.html',
        name: 'PDF to TIFF',
        icon: 'file-image',
        subtitle: 'Convert each PDF page into a TIFF image.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-greyscale.html',
        name: 'PDF to Greyscale',
        icon: 'palette',
        subtitle: 'Convert all colors to black and white.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-json.html',
        name: 'PDF to JSON',
        icon: 'file-code',
        subtitle: 'Convert PDF files to JSON format.',
      },
    ],
  },
  {
    name: 'Organize & Manage',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'ocr-pdf.html',
        name: 'OCR PDF',
        icon: 'scan-text',
        subtitle: 'Make a PDF searchable and copyable.',
      },
      {
        href: import.meta.env.BASE_URL + 'merge-pdf.html',
        name: 'Merge PDF',
        icon: 'combine',
        subtitle: 'Combine multiple PDFs into one file.',
      },
      {
        href: import.meta.env.BASE_URL + 'alternate-merge.html',
        name: 'Alternate & Mix Pages',
        icon: 'shuffle',
        subtitle: 'Merge PDFs by alternating pages from each PDF. Preserves Bookmarks',
      },
      {
        href: import.meta.env.BASE_URL + 'organize-pdf.html',
        name: 'Organize & Duplicate',
        icon: 'files',
        subtitle: 'Duplicate, reorder, and delete pages.',
      },
      {
        href: import.meta.env.BASE_URL + 'add-attachments.html',
        name: 'Add Attachments',
        icon: 'paperclip',
        subtitle: 'Embed one or more files into your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'extract-attachments.html',
        name: 'Extract Attachments',
        icon: 'download',
        subtitle: 'Extract all embedded files from PDF(s) as a ZIP.',
      },
      {
        href: import.meta.env.BASE_URL + 'edit-attachments.html',
        name: 'Edit Attachments',
        icon: 'file-edit',
        subtitle: 'View or remove attachments in your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-multi-tool.html',
        name: 'PDF Multi Tool',
        icon: 'pencil-ruler',
        subtitle: 'Full-featured PDF editor with page management.',
      },
      {
        href: import.meta.env.BASE_URL + 'split-pdf.html',
        name: 'Split PDF',
        icon: 'scissors',
        subtitle: 'Extract a range of pages into a new PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'divide-pages.html',
        name: 'Divide Pages',
        icon: 'table-columns-split',
        subtitle: 'Divide pages horizontally or vertically.',
      },
      {
        href: import.meta.env.BASE_URL + 'extract-pages.html',
        name: 'Extract Pages',
        icon: 'ungroup',
        subtitle: 'Save a selection of pages as new files.',
      },
      {
        href: import.meta.env.BASE_URL + 'delete-pages.html',
        name: 'Delete Pages',
        icon: 'trash-2',
        subtitle: 'Remove specific pages from your document.',
      },
      {
        href: import.meta.env.BASE_URL + 'add-blank-page.html',
        name: 'Add Blank Page',
        icon: 'file-plus-2',
        subtitle: 'Insert an empty page anywhere in your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'reverse-pages.html',
        name: 'Reverse Pages',
        icon: 'arrow-down-z-a',
        subtitle: 'Flip the order of all pages in your document.',
      },
      {
        href: import.meta.env.BASE_URL + 'rotate-pdf.html',
        name: 'Rotate PDF',
        icon: 'rotate-cw',
        subtitle: 'Turn pages in 90-degree increments.',
      },
      {
        href: import.meta.env.BASE_URL + 'n-up-pdf.html',
        name: 'N-Up PDF',
        icon: 'layout-grid',
        subtitle: 'Arrange multiple pages onto a single sheet.',
      },
      {
        href: import.meta.env.BASE_URL + 'combine-single-page.html',
        name: 'Combine to Single Page',
        icon: 'unfold-vertical',
        subtitle: 'Stitch all pages into one continuous scroll.',
      },
      {
        href: import.meta.env.BASE_URL + 'view-metadata.html',
        name: 'View Metadata',
        icon: 'info',
        subtitle: 'Inspect the hidden properties of your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'edit-metadata.html',
        name: 'Edit Metadata',
        icon: 'file-cog',
        subtitle: 'Change the author, title, and other properties.',
      },
      {
        href: import.meta.env.BASE_URL + 'pdf-to-zip.html',
        name: 'PDFs to ZIP',
        icon: 'stretch-horizontal',
        subtitle: 'Package multiple PDF files into a ZIP archive.',
      },
      {
        href: import.meta.env.BASE_URL + 'compare-pdfs.html',
        name: 'Compare PDFs',
        icon: 'git-compare',
        subtitle: 'Compare two PDFs side by side.',
      },
      {
        href: import.meta.env.BASE_URL + 'posterize-pdf.html',
        name: 'Posterize PDF',
        icon: 'notepad-text-dashed',
        subtitle: 'Split a large page into multiple smaller pages.',
      },
    ],
  },
  {
    name: 'Optimize & Repair',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'compress-pdf.html',
        name: 'Compress PDF',
        icon: 'zap',
        subtitle: 'Reduce the file size of your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'fix-page-size.html',
        name: 'Fix Page Size',
        icon: 'ruler-dimension-line',
        subtitle: 'Standardize all pages to a uniform size.',
      },
      {
        href: import.meta.env.BASE_URL + 'linearize-pdf.html',
        name: 'Linearize PDF',
        icon: 'gauge',
        subtitle: 'Optimize PDF for fast web viewing.',
      },
      {
        href: import.meta.env.BASE_URL + 'page-dimensions.html',
        name: 'Page Dimensions',
        icon: 'ruler',
        subtitle: 'Analyze page size, orientation, and units.',
      },
      {
        href: import.meta.env.BASE_URL + 'remove-restrictions.html',
        name: 'Remove Restrictions',
        icon: 'unlink',
        subtitle:
          'Remove password protection and security restrictions associated with digitally signed PDF files.',
      },
      {
        href: import.meta.env.BASE_URL + 'repair-pdf.html',
        name: 'Repair PDF',
        icon: 'wrench',
        subtitle: 'Recover data from corrupted or damaged PDF files.',
      },
    ],
  },
  {
    name: 'Secure PDF',
    tools: [
      {
        href: import.meta.env.BASE_URL + 'encrypt-pdf.html',
        name: 'Encrypt PDF',
        icon: 'lock',
        subtitle: 'Lock your PDF by adding a password.',
      },
      {
        href: import.meta.env.BASE_URL + 'sanitize-pdf.html',
        name: 'Sanitize PDF',
        icon: 'brush-cleaning',
        subtitle: 'Remove metadata, annotations, scripts, and more.',
      },
      {
        href: import.meta.env.BASE_URL + 'decrypt-pdf.html',
        name: 'Decrypt PDF',
        icon: 'unlock',
        subtitle: 'Unlock PDF by removing password protection.',
      },
      {
        href: import.meta.env.BASE_URL + 'flatten-pdf.html',
        name: 'Flatten PDF',
        icon: 'layers',
        subtitle: 'Make form fields and annotations non-editable.',
      },
      {
        href: import.meta.env.BASE_URL + 'remove-metadata.html',
        name: 'Remove Metadata',
        icon: 'file-x',
        subtitle: 'Strip hidden data from your PDF.',
      },
      {
        href: import.meta.env.BASE_URL + 'change-permissions.html',
        name: 'Change Permissions',
        icon: 'shield-check',
        subtitle: 'Set or change user permissions on a PDF.',
      },
    ],
  },
];
